/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookmarkType = IDL.Variant({
  'word' : IDL.Null,
  'phrase' : IDL.Null,
});
export const BookmarkEntry = IDL.Record({
  'bookmarkType' : BookmarkType,
  'meaning' : IDL.Text,
  'word' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Bookmark = IDL.Record({
  'id' : IDL.Nat,
  'bookmarkType' : BookmarkType,
  'meaning' : IDL.Text,
  'word' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PracticeQuestion = IDL.Record({
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const GrammarLesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'explanation' : IDL.Text,
  'practiceQuestions' : IDL.Vec(PracticeQuestion),
  'category' : IDL.Text,
  'examples' : IDL.Vec(IDL.Text),
});
export const IdiomCategory = IDL.Variant({
  'expression' : IDL.Null,
  'idiom' : IDL.Null,
  'phrase' : IDL.Null,
});
export const IdiomPhrase = IDL.Record({
  'id' : IDL.Nat,
  'exampleSentence' : IDL.Text,
  'meaning' : IDL.Text,
  'term' : IDL.Text,
  'category' : IdiomCategory,
  'usageExplanation' : IDL.Text,
});
export const PronunciationWord = IDL.Record({
  'id' : IDL.Nat,
  'word' : IDL.Text,
  'category' : IDL.Text,
  'phonetic' : IDL.Text,
});
export const QuestionType = IDL.Variant({
  'fillBlank' : IDL.Null,
  'sentenceCorrection' : IDL.Null,
  'multipleChoice' : IDL.Null,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'options' : IDL.Vec(IDL.Text),
});
export const WordOfDay = IDL.Record({
  'meaning' : IDL.Text,
  'word' : IDL.Text,
  'example' : IDL.Text,
  'phonetic' : IDL.Text,
  'wordType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([BookmarkEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGrammarLessons' : IDL.Func([], [IDL.Vec(GrammarLesson)], ['query']),
  'getIdiomsPhrases' : IDL.Func([], [IDL.Vec(IdiomPhrase)], ['query']),
  'getPronunciationWords' : IDL.Func(
      [],
      [IDL.Vec(PronunciationWord)],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWordOfDay' : IDL.Func([], [IDL.Opt(WordOfDay)], ['query']),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setWordOfDay' : IDL.Func([WordOfDay], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookmarkType = IDL.Variant({ 'word' : IDL.Null, 'phrase' : IDL.Null });
  const BookmarkEntry = IDL.Record({
    'bookmarkType' : BookmarkType,
    'meaning' : IDL.Text,
    'word' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Bookmark = IDL.Record({
    'id' : IDL.Nat,
    'bookmarkType' : BookmarkType,
    'meaning' : IDL.Text,
    'word' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PracticeQuestion = IDL.Record({
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const GrammarLesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'explanation' : IDL.Text,
    'practiceQuestions' : IDL.Vec(PracticeQuestion),
    'category' : IDL.Text,
    'examples' : IDL.Vec(IDL.Text),
  });
  const IdiomCategory = IDL.Variant({
    'expression' : IDL.Null,
    'idiom' : IDL.Null,
    'phrase' : IDL.Null,
  });
  const IdiomPhrase = IDL.Record({
    'id' : IDL.Nat,
    'exampleSentence' : IDL.Text,
    'meaning' : IDL.Text,
    'term' : IDL.Text,
    'category' : IdiomCategory,
    'usageExplanation' : IDL.Text,
  });
  const PronunciationWord = IDL.Record({
    'id' : IDL.Nat,
    'word' : IDL.Text,
    'category' : IDL.Text,
    'phonetic' : IDL.Text,
  });
  const QuestionType = IDL.Variant({
    'fillBlank' : IDL.Null,
    'sentenceCorrection' : IDL.Null,
    'multipleChoice' : IDL.Null,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'options' : IDL.Vec(IDL.Text),
  });
  const WordOfDay = IDL.Record({
    'meaning' : IDL.Text,
    'word' : IDL.Text,
    'example' : IDL.Text,
    'phonetic' : IDL.Text,
    'wordType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([BookmarkEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGrammarLessons' : IDL.Func([], [IDL.Vec(GrammarLesson)], ['query']),
    'getIdiomsPhrases' : IDL.Func([], [IDL.Vec(IdiomPhrase)], ['query']),
    'getPronunciationWords' : IDL.Func(
        [],
        [IDL.Vec(PronunciationWord)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWordOfDay' : IDL.Func([], [IDL.Opt(WordOfDay)], ['query']),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setWordOfDay' : IDL.Func([WordOfDay], [], []),
  });
};

export const init = ({ IDL }) => { return []; };