/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bookmark {
  'id' : bigint,
  'bookmarkType' : BookmarkType,
  'meaning' : string,
  'word' : string,
}
export interface BookmarkEntry {
  'bookmarkType' : BookmarkType,
  'meaning' : string,
  'word' : string,
}
export type BookmarkType = { 'word' : null } |
  { 'phrase' : null };
export interface GrammarLesson {
  'id' : bigint,
  'title' : string,
  'explanation' : string,
  'practiceQuestions' : Array<PracticeQuestion>,
  'category' : string,
  'examples' : Array<string>,
}
export type IdiomCategory = { 'expression' : null } |
  { 'idiom' : null } |
  { 'phrase' : null };
export interface IdiomPhrase {
  'id' : bigint,
  'exampleSentence' : string,
  'meaning' : string,
  'term' : string,
  'category' : IdiomCategory,
  'usageExplanation' : string,
}
export interface PracticeQuestion {
  'question' : string,
  'explanation' : string,
  'correctAnswer' : string,
  'options' : Array<string>,
}
export interface PronunciationWord {
  'id' : bigint,
  'word' : string,
  'category' : string,
  'phonetic' : string,
}
export type QuestionType = { 'fillBlank' : null } |
  { 'sentenceCorrection' : null } |
  { 'multipleChoice' : null };
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'explanation' : string,
  'correctAnswer' : string,
  'questionType' : QuestionType,
  'options' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WordOfDay {
  'meaning' : string,
  'word' : string,
  'example' : string,
  'phonetic' : string,
  'wordType' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[BookmarkEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBookmarks' : ActorMethod<[], Array<Bookmark>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGrammarLessons' : ActorMethod<[], Array<GrammarLesson>>,
  'getIdiomsPhrases' : ActorMethod<[], Array<IdiomPhrase>>,
  'getPronunciationWords' : ActorMethod<[], Array<PronunciationWord>>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWordOfDay' : ActorMethod<[], [] | [WordOfDay]>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBookmark' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setWordOfDay' : ActorMethod<[WordOfDay], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];