/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BookmarkEntry {
    bookmarkType: BookmarkType;
    meaning: string;
    word: string;
}
export interface IdiomPhrase {
    id: bigint;
    exampleSentence: string;
    meaning: string;
    term: string;
    category: IdiomCategory;
    usageExplanation: string;
}
export interface GrammarLesson {
    id: bigint;
    title: string;
    explanation: string;
    practiceQuestions: Array<PracticeQuestion>;
    category: string;
    examples: Array<string>;
}
export interface QuizQuestion {
    id: bigint;
    question: string;
    explanation: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}
export interface PronunciationWord {
    id: bigint;
    word: string;
    category: string;
    phonetic: string;
}
export interface WordOfDay {
    meaning: string;
    word: string;
    example: string;
    phonetic: string;
    wordType: string;
}
export interface Bookmark {
    id: bigint;
    bookmarkType: BookmarkType;
    meaning: string;
    word: string;
}
export interface PracticeQuestion {
    question: string;
    explanation: string;
    correctAnswer: string;
    options: Array<string>;
}
export interface UserProfile {
    name: string;
}
export enum BookmarkType {
    word = "word",
    phrase = "phrase"
}
export enum IdiomCategory {
    expression = "expression",
    idiom = "idiom",
    phrase = "phrase"
}
export enum QuestionType {
    fillBlank = "fillBlank",
    sentenceCorrection = "sentenceCorrection",
    multipleChoice = "multipleChoice"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBookmark(entry: BookmarkEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getBookmarks(): Promise<Array<Bookmark>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGrammarLessons(): Promise<Array<GrammarLesson>>;
    getIdiomsPhrases(): Promise<Array<IdiomPhrase>>;
    getPronunciationWords(): Promise<Array<PronunciationWord>>;
    getQuizQuestions(): Promise<Array<QuizQuestion>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWordOfDay(): Promise<WordOfDay | null>;
    initializeSystem(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeBookmark(bookmarkId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setWordOfDay(newWord: WordOfDay): Promise<void>;
}
import type { Bookmark as _Bookmark, BookmarkEntry as _BookmarkEntry, BookmarkType as _BookmarkType, IdiomCategory as _IdiomCategory, IdiomPhrase as _IdiomPhrase, QuestionType as _QuestionType, QuizQuestion as _QuizQuestion, UserProfile as _UserProfile, UserRole as _UserRole, WordOfDay as _WordOfDay } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBookmark(arg0: BookmarkEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(to_candid_BookmarkEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(to_candid_BookmarkEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getBookmarks(): Promise<Array<Bookmark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarks();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarks();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrammarLessons(): Promise<Array<GrammarLesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrammarLessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrammarLessons();
            return result;
        }
    }
    async getIdiomsPhrases(): Promise<Array<IdiomPhrase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdiomsPhrases();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdiomsPhrases();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPronunciationWords(): Promise<Array<PronunciationWord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPronunciationWords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPronunciationWords();
            return result;
        }
    }
    async getQuizQuestions(): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWordOfDay(): Promise<WordOfDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWordOfDay();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWordOfDay();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSystem(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSystem();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeBookmark(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setWordOfDay(arg0: WordOfDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWordOfDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWordOfDay(arg0);
            return result;
        }
    }
}
function from_candid_BookmarkType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookmarkType): BookmarkType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Bookmark_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bookmark): Bookmark {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_IdiomCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdiomCategory): IdiomCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_IdiomPhrase_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdiomPhrase): IdiomPhrase {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_QuizQuestion_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizQuestion): QuizQuestion {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WordOfDay]): WordOfDay | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exampleSentence: string;
    meaning: string;
    term: string;
    category: _IdiomCategory;
    usageExplanation: string;
}): {
    id: bigint;
    exampleSentence: string;
    meaning: string;
    term: string;
    category: IdiomCategory;
    usageExplanation: string;
} {
    return {
        id: value.id,
        exampleSentence: value.exampleSentence,
        meaning: value.meaning,
        term: value.term,
        category: from_candid_IdiomCategory_n18(_uploadFile, _downloadFile, value.category),
        usageExplanation: value.usageExplanation
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    question: string;
    explanation: string;
    correctAnswer: string;
    questionType: _QuestionType;
    options: Array<string>;
}): {
    id: bigint;
    question: string;
    explanation: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
} {
    return {
        id: value.id,
        question: value.question,
        explanation: value.explanation,
        correctAnswer: value.correctAnswer,
        questionType: from_candid_QuestionType_n23(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bookmarkType: _BookmarkType;
    meaning: string;
    word: string;
}): {
    id: bigint;
    bookmarkType: BookmarkType;
    meaning: string;
    word: string;
} {
    return {
        id: value.id,
        bookmarkType: from_candid_BookmarkType_n10(_uploadFile, _downloadFile, value.bookmarkType),
        meaning: value.meaning,
        word: value.word
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    word: null;
} | {
    phrase: null;
}): BookmarkType {
    return "word" in value ? BookmarkType.word : "phrase" in value ? BookmarkType.phrase : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expression: null;
} | {
    idiom: null;
} | {
    phrase: null;
}): IdiomCategory {
    return "expression" in value ? IdiomCategory.expression : "idiom" in value ? IdiomCategory.idiom : "phrase" in value ? IdiomCategory.phrase : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fillBlank: null;
} | {
    sentenceCorrection: null;
} | {
    multipleChoice: null;
}): QuestionType {
    return "fillBlank" in value ? QuestionType.fillBlank : "sentenceCorrection" in value ? QuestionType.sentenceCorrection : "multipleChoice" in value ? QuestionType.multipleChoice : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IdiomPhrase>): Array<IdiomPhrase> {
    return value.map((x)=>from_candid_IdiomPhrase_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizQuestion>): Array<QuizQuestion> {
    return value.map((x)=>from_candid_QuizQuestion_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bookmark>): Array<Bookmark> {
    return value.map((x)=>from_candid_Bookmark_n8(_uploadFile, _downloadFile, x));
}
function to_candid_BookmarkEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookmarkEntry): _BookmarkEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BookmarkType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookmarkType): _BookmarkType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookmarkType: BookmarkType;
    meaning: string;
    word: string;
}): {
    bookmarkType: _BookmarkType;
    meaning: string;
    word: string;
} {
    return {
        bookmarkType: to_candid_BookmarkType_n3(_uploadFile, _downloadFile, value.bookmarkType),
        meaning: value.meaning,
        word: value.word
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookmarkType): {
    word: null;
} | {
    phrase: null;
} {
    return value == BookmarkType.word ? {
        word: null
    } : value == BookmarkType.phrase ? {
        phrase: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
